### PR TITLE
Fixed unhandled errors

### LINKED ISSUE #5: plumber doesn't work
My watchers stoped when js errored. I think, you need to catch error of js parser and throw it by callback.

### PR DESCRIPTION
**Pull request by TrySound**
fix #5 

@RReverser Take a look ASAP, please!

### CODE REVIEW

**Comment by TrySound** [comment]
@RReverser Up!

**Comment by TrySound** [comment]
@RReverser Up, please!

File: index.js [hunk 1]
```diff
@@ -20,40 +21,42 @@ module.exports = function (tmpl, format) {
 
 		// Do nothing if no contents
 		if (file.isNull()) {
-			this.push(file);
-			return callback();
+			callback(null, file);
```
Comment (RReverser) [inline index.js]: Please put back `return`.

File: index.js [hunk 2]
```diff
@@ -20,40 +21,42 @@ module.exports = function (tmpl, format) {
...
 		}
 
 		if (file.isStream()) {
-			this.emit('error', new gutil.PluginError('gulp-wrap-js', 'Stream content is not supported'));
-			return callback();
+			callback(new gutil.PluginError('gulp-wrap-js', 'Stream content is not supported'));
```
Comment (RReverser) [inline index.js]: Same here.

File: index.js [hunk 3]
```diff
@@ -20,40 +21,42 @@ module.exports = function (tmpl, format) {
...
+					format: format,
+					sourceMap: true,
+					sourceMapWithCode: true,
+					file: file.relative
+				});
+				file.contents = new Buffer(result.code);
+				if (file.sourceMap) {
+					applySourceMap(file, JSON.parse(result.map.toString()));
+				}
+				callback(null, file);
```
Comment (RReverser) [inline index.js]: Don't put `callback(...)` inside of `try-catch` - it's external error.

File: index.js (hunk 1 above)
Comment (TrySound) [inline index.js]: Why? Nothing more after it.

Comment (RReverser) [inline index.js]: Part of coding style - 1) no sense to do extra checks like `file.isStream()`, `file.isBuffer()` after invoking callback and 2) lower risk of "gotcha" if adding some new code to the function in future.

File: index.js (hunk 3 above)
Comment (TrySound) [inline index.js]: @RReverser  Done.

File: index.js (hunk 1 above)
Comment (TrySound) [inline index.js]: @RReverser Done.

File: index.js [hunk 4]
```diff
@@ -20,40 +21,48 @@ module.exports = function (tmpl, format) {
...
+				err = e;
 			}
-			this.push(file);
-		}
 
-		return callback();
+			if(err) {
+				// Relative to gulpfile.js filepath with forward slashes
+				file = gutil.colors.magenta(path.relative('.', file.path).split(path.sep).join('/'));
+				callback(new gutil.PluginError('gulp-wrap-js', file + ' ' + err.message))
```
Comment (RReverser) [inline index.js]: Also - put `return` here and move it inside the `catch` block so that you wouldn't need temporary variable and separate `if-else` block at all.

**Comment by TrySound** [comment]
Also need to update dependencies

**Comment by TrySound** [comment]
@RReverser Is it ok now?

**Comment by psychowico** [comment]
+1 I waiting for this too.

**Comment by TrySound** [comment]
@psychowico You can use now my fork as a dependency, until @RReverser busy.

**Comment by RReverser** [comment]
Pushed to npm as 0.2.2.
Thank you for contribution and waiting!

**Comment by TrySound** [comment]
@RReverser Oh, thanks!
